# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: HistoryForge
email: historyforge@thehistorycenter.net
description: >- # this means to ignore newlines until "baseurl:"
  HistoryForge combines historic maps and photos with census records of the people
  who lived in a city or town, creating a unique way to visualize the history of 
  the community in the early 1900s.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://historyforge.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
sass:
  style: compressed
include: ['_pages']

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - gulpfile.js
 - package.json
 - package-lock.json
 - assets/scss/
 - .idea/

# Project Documentation Links
project_links:
- name: Transcription
  links:
  - name: Transcription Convention
    url: https://docs.google.com/document/d/1MFZO9GkxSaQ0GJF3zrLP2TIjrlL9EIZ-3E5s1zaTS4Y
  - name: "FamilySearch's Handwriting Helps: Alphabet (Secretary Hand)"
    url: https://www.familysearch.org/indexing/help/handwriting#!/lang=en&title=Alphabet%20(Secretary%20Hand)

- name: Buildings
  links:
  - name: Buildings Manual
    url: https://docs.google.com/document/d/1PAUiZQKXMrJSVuU_HWU2z5dJHzBf-cszAvS7sw_UsJY

- name: Admin Menu
  links:
  - name: Adding Photographs
    url: https://docs.google.com/document/d/1N8n4TRJgRzTlv-aTHGHY8_g7_xddxoBTKejXbHs6cBU
  - name: Controlled Vocabularies
    url: https://docs.google.com/document/d/1tKe4AmiXytbWTb8H4__ayh9oQGZmS7K4VIbaQhtPXFc
  - name: "Transcriber Resources on the Resources & Credits page"
    url: https://docs.google.com/document/d/1lLpw-Kza9_IGF4hDgGjk6SxXYJHFUWicaV1n5CDWAfE
  - name: Flagged Content
    url: https://docs.google.com/document/d/1Mapp-vCpVtw-3Z0g0ceD4tvofNOZigY3ML-JN7MHX9Y
  - name: Localities
    url: https://docs.google.com/document/d/1QaXxhhlwwDHvZ5acgk_1RzcZoOw3MzP9rJTFQVyiOrE
  - name: Map Overlays
    url: https://docs.google.com/document/d/1Wu302EayiWQVsraZtpPdWryoMEelyKlzKnAponSFEUQ
  - name: Rebuild Index
    url: https://docs.google.com/document/d/1cgKgHOqzns3lGTCFWziP-1Nx5wJwP_xf12WSLg-zwpk
  - name: Street Conversions
    url: https://docs.google.com/document/d/1gikT4cJ3Bb_cFMXeGx32JEebi8DJzzuxY19u1h3c4e0
  - name: User Accounts
    url: https://docs.google.com/document/d/1x7QXDM1WUU3X9IdzFGV2niiV7MFnJojA2jsEAfesBQw

- name: General HF Project Admin
  links:
  - name: Current HF Street Suffixes
    url: https://docs.google.com/document/d/17sxsfnByKMRROlbPmxO8pw9cqDWV1xyQXp_cY756yxE
  - name: Example HistoryForge Volunteer Application Google Form from Tompkins HF
    url: https://docs.google.com/forms/d/1XTtppF6IA4tl27Pq-W1x1m4HzirTkxboF8GRHwhlAss
  - name: Example 1850-1930 Census Tracking Spreadsheet
    url: https://docs.google.com/spreadsheets/d/1ix992YsipPO3j4Vh_m6cO388CJZZMCPrqrdhAHLmh-A
  - name: Example 1940 Census Tracking Spreadsheet
    url: https://docs.google.com/spreadsheets/d/1s1VcBLKQ5k8U2NHvRP1NVI0olvRkbUMuplGZ3kYVzVw
  - name: Example 1950 Census Tracking Spreadsheet
    url: https://docs.google.com/spreadsheets/d/1sz3tLxrHku3s3kaKPOX6Qwljbo6lgdS_vl4BUy1V7A8
  - name: Example Ithaca Street Name Changes 1880-1950
    url: https://docs.google.com/spreadsheets/d/1_rjDZ2Jg_ZVpgNk0DpZftP4NoXI8SiDeqFp0GuFX_T0
  - name: Preparing to Bring HistoryForge to Your Community
    url: https://docs.google.com/document/d/1oo5iq5iL31AhOUJCSxAH3t07q1pRCPtvTH4_8D8dSD0
  - name: "Your HistoryForge Installation-A Quick Start Guide for Project Administrators"
    url: https://docs.google.com/document/d/1FJeqNwKXxDfFz0ypNhaF-EZhN2saK6IlyYtM53GDFLE

- name: How to Search HistoryForge
  links:
  - name: How to HistoryForge-Basic Searches
    url: https://docs.google.com/document/d/1cguTJWvcDzMpWB6vinFGDRXNlNisZTKFaqn_pgliFzk
  - name: "How to HistoryForge: Using the Census to Explore Your Community's History"
    url: https://docs.google.com/document/d/1tvzjGZ7rkhhnnnLEsRVfobh9JwNx8djtzEnJ2rXvQlc

- name: MapWarper
  links:
  - name: HistoryForge MapWarper Manual
    url: https://docs.google.com/document/d/1mEgzMuOgNezgBwi-mAp0Blo6qPwcb5sa8llbF4mW4Ko

- name: 1850 Census Transcriber Resources
  links:
  - name: List of Questions Asked on the 1850 Census
    url: https://docs.google.com/document/d/1TjAbTNUTucdiN7EWPVamXjQBJogCp2t67Rpoy9gdodk
  - name: HistoryForge 1850 Census Manual
    url: https://docs.google.com/document/d/13x0cTEbhXGV2kiRfaCyK4UbTTLzE58_4bbBonEvd8Uc
  - name: 1850 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1wF_FeWrzdscOk3xLaULeLlU5_dMQr3s1jitO8QKFqdo

- name: 1860 Census Transcriber Resources
  links:
  - name: List of Questions Asked on the 1860 Census
    url: https://docs.google.com/document/d/1LIYvj8JJpT7rWsKABjeOyiozRU2bQBaJbEJ-a_hYAN8
  - name: HistoryForge 1860 Census Manual
    url: https://docs.google.com/document/d/1RhJwwJrAs19fLb7Xz2eZL1nRhCXm2uBwsbhYgR8e_hY
  - name: 1860 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1EIGGrcNS-vtuJErBGUhjy-eItHvuOneNlbPbtXVOZx4

- name: 1870 Census Transcriber Resources
  links: 
  - name: List of Questions Asked on the 1870 Census
    url: https://docs.google.com/document/d/1djjKFAU_wgz_6gZZRQLJ41_84PmHjH_ro6pyYxO5xGw
  - name: HistoryForge 1870 Census Manual
    url: https://docs.google.com/document/d/1a1ROs-ZQouB_nBsT6I0jVIYTgWZzABDZF7M0ttZg4Js
  - name: 1870 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1k_TwfByABgCk1fwsQKHQeI03vIh00HiFXS6vO5aYD0s

- name: 1880 Census Transcriber Resources
  links:
  - name: List of Questions Asked on the 1880 Census
    url: https://docs.google.com/document/d/1bzhz4AslspL41vDMBN5U6d_ykHCBmHUO7ZHwic81AOo
  - name: HistoryForge 1880 Census Manual
    url: https://docs.google.com/document/d/1kwuPoJZ6r9gMW_wG3VQvuDUkW2m-PEXhP25_thTkGiw
  - name: 1880 Census Sickness on Day of Enumeration
    url: https://docs.google.com/spreadsheets/d/1HVfVQ4ox0kw0-rjvhVTXbWWFXG4JXwmBwuA7D94cdrw
  - name: 1880 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1_ajejYEuSQmUgj18_s5WZXPkKf7tdwbhnxfVdi1XkyQ

- name: 1900 Census Transcriber Resources
  links: 
  - name: List of Questions Asked on the 1900 Census
    url: https://docs.google.com/document/d/1_lMIipxXIXrMbGWACocaAWgpfzv9cPSzrUF93HnLuUc
  - name: HistoryForge 1900 Census Manual
    url: https://docs.google.com/document/d/1gRqdTk_-GBPUfD6txoA8qkPWCXef48U3dEiEZ2UlRo8
  - name: 1900 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1gyhOEnqIJ9UsbheIN9G4D-gdCf6eZVP1-0R8DcXGFMw

- name: 1910 Census Transcriber Resources
  links:
  - name: List of Questions Asked on the 1910 Census
    url: https://docs.google.com/document/d/10s_yYT5SFzJTeichP-P1D7mus6H0vX4P03OaPqttOGg
  - name: HistoryForge 1910 Census Manual
    url: https://docs.google.com/document/d/1wCPdGDje7Ub-Sh7EsdwuL7lmzL4UfxQDr9smockwtKY
  - name: 1910 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1EgB47Y7HlIGOej28uetL5BSZTR7sCeDIlKUtQzgklns

- name: 1920 Census Transcriber Resources
  links:
  - name: List of Questions Asked on the 1920 Census
    url: https://docs.google.com/document/d/1CwbfNJJBc1PhNThIWROsOi_Ij9EXFf5szvaElYHuR9g
  - name: HistoryForge 1920 Census Manual
    url: https://docs.google.com/document/d/1TNQX2F6kT_nu4NQcphsDy1lXmy0TCIUPU0M8E4QR7n4
  - name: How to Verify Occupation Codes on the 1920 Census
    url: https://docs.google.com/document/d/13iJVlSv5o8cOcKZ29A3rkfQ9x2DYaGBWdxX5IvjFV0M
  - name: 1920 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1YLlONp8dU7k0JY4SEQ8xmfvaZGqh8gYNi9z_Rf8aCf4

- name: 1930 Census Transcriber Resources
  links:
  - name: List of Questions Asked on the 1930 Census
    url: https://docs.google.com/document/d/1EUztLpa3eyNjykpYkblJ_7AfjaaeSClsrP_Guadn-So
  - name: HistoryForge 1930 Census Manual
    url: https://docs.google.com/document/d/1uW-R0PCHV6GQU4Ba2kTXetGv3OlgeX7FNlF8rlKEPxE
  - name: How to Verify Occupation Codes on the 1930 Census
    url: https://docs.google.com/document/d/1V-d2BbDAmESarsIdmLjc-avuj3m51bQ4fHYl8FF2Wkk/edit#heading=h.q6rqmy64vrb6
  - name: 1930 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1lfU-kb7c8ii8zuI_fQYgYQ-cGvlEuUQ8qklFpHknK84

- name: 1940 Census Transcriber Resources
  links:
  - name: List of Questions Asked on the 1940 Census
    url: https://docs.google.com/document/d/1ZH0CvFUui8wmKkSrc4wOyLtS0Wey-cYZfAZnD3Om94U
  - name: HistoryForge 1940 Census Manual
    url: https://docs.google.com/document/d/1ONNUX9SS5qOX8Up0blD2uv-DXYtHRhh--orGfFUQl9Q
  - name: How to Verify Occupation and Industry Codes on the 1940 CensusList of Questions Asked on the 1950 Census
    url: https://docs.google.com/document/d/1QNI_EVOPVdks6vChm7V1HJwlCnMsvZvx-_VbdlxYABQ
  - name: 1940 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1IAWxHXG9NHze-M8Q3dt8KUFQj4OiMYP9Rl2mbh-4M6k

- name: 1950 Census Transcriber Resources
  links:
  - name: List of Questions Asked on the 1950 Census
    url: https://docs.google.com/document/d/1FLzRZlivq4DSFpV7OFv24kO1eSHYwM5Xs7Xp0vSA4Xg
  - name: HistoryForge 1950 Census Manual
    url: https://docs.google.com/document/d/1fnD8tAvCKE9vJS-b1hK4Oe5q_CV5R-WylWyX46vobZk
  - name: How to Verify Occupation/Industry/Worker Class Codes on the 1950 Census
    url: https://docs.google.com/spreadsheets/d/1GiWDPiKGyZZHLDxSG-ZCazRcwQ4E9cFoMGlDnXurL-4
  - name: 1950 Census Self-Review Checklist
    url: https://docs.google.com/document/d/1vqqO2gS8NWUpLEcfdnArxJLfr96OfrzIpLSV-Ulz-9I

- name: 1850 Census Review and Other Documents
  links:
  - name: 1850 Census Reviewers Guidelines
    url: https://docs.google.com/document/d/1rE6jxklnE0UjXKyHcPndWoXshNoVSHFJUM-iRkkNv0g
  - name: 1850 Census: History Enumerators Instructions and More
    url: https://docs.google.com/document/d/11HWOtBF24tkr1YauAHzrhFUfwiHwoQV7F44K7YjyI6M
  
  
    



  


  
